<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Approvals</label>
    <navType>Console</navType>
    <tabs>standard-ApprovalsHome</tabs>
    <tabs>vaultA__c</tabs>
    <tabs>vaultB__c</tabs>
    <tabs>vaultC__c</tabs>
    <tabs>vaultD__c</tabs>
    <tabs>vaultE__c</tabs>
    <tabs>vaultF__c</tabs>
    <tabs>vaultG__c</tabs>
    <tabs>vaultJ__c</tabs>
    <tabs>vaultK__c</tabs>
    <tabs>vaultL__c</tabs>
    <tabs>vaultM__c</tabs>
    <tabs>vaultN__c</tabs>
    <tabs>vaultO__c</tabs>
    <tabs>vaultP__c</tabs>
    <tabs>vaultH__c</tabs>
    <tabs>RTA_C_JAHEER__c</tabs>
    <tabs>RichTextArea_jaheer__c</tabs>
    <tabs>RabitParent__c</tabs>
    <tabs>IncBup_Regression_25_2__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>IncBup_Regression_25_2__c</tab>
        </mappings>
        <mappings>
            <tab>RTA_C_JAHEER__c</tab>
        </mappings>
        <mappings>
            <tab>RabitParent__c</tab>
        </mappings>
        <mappings>
            <tab>RichTextArea_jaheer__c</tab>
        </mappings>
        <mappings>
            <tab>standard-ApprovalsHome</tab>
        </mappings>
        <mappings>
            <tab>vaultA__c</tab>
        </mappings>
        <mappings>
            <tab>vaultB__c</tab>
        </mappings>
        <mappings>
            <tab>vaultC__c</tab>
        </mappings>
        <mappings>
            <tab>vaultD__c</tab>
        </mappings>
        <mappings>
            <tab>vaultE__c</tab>
        </mappings>
        <mappings>
            <tab>vaultF__c</tab>
        </mappings>
        <mappings>
            <tab>vaultG__c</tab>
        </mappings>
        <mappings>
            <tab>vaultH__c</tab>
        </mappings>
        <mappings>
            <tab>vaultJ__c</tab>
        </mappings>
        <mappings>
            <tab>vaultK__c</tab>
        </mappings>
        <mappings>
            <tab>vaultL__c</tab>
        </mappings>
        <mappings>
            <tab>vaultM__c</tab>
        </mappings>
        <mappings>
            <tab>vaultN__c</tab>
        </mappings>
        <mappings>
            <tab>vaultO__c</tab>
        </mappings>
        <mappings>
            <tab>vaultP__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
